ERROR - 2021-01-14 14:00:36 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:00:36 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:00:37 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:00:48 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('admin', 'Password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:00:48 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('admin', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('admin')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('admin', 'Password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:00:48 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('admin')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('admin', 'Password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:01:20 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'Password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:01:20 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'Password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:01:20 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'Password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:02:09 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:02:09 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('admin@admin.com', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('admin@admin.com')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:02:09 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('admin@admin.com')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('admin@admin.com', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:02:42 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:02:42 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:02:42 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:03:04 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:03:04 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:03:05 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:03:50 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', true)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:03:50 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', true)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:03:50 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', true)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:05:34 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:05:34 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:05:34 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:07:09 --> mysqli_sql_exception: Can't create database 'bitnami_app'; database exists in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('CREATE DATABASE...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('CREATE DATABASE...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE DATABASE...')
#3 /var/www/system/Database/Forge.php(222): CodeIgniter\Database\BaseConnection->query('CREATE DATABASE...')
#4 /var/www/system/Commands/Database/CreateDatabase.php(146): CodeIgniter\Database\Forge->createDatabase('bitnami_app')
#5 /var/www/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\CreateDatabase->run(Array)
#6 /var/www/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:create', Array)
#7 /var/www/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#8 /var/www/system/CodeIgniter.php(927): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:create')
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#12 /var/www/spark(68): CodeIgniter\CLI\Console->run()
#13 {main}
ERROR - 2021-01-14 14:07:27 --> mysqli_sql_exception: Table 'bitnami_app.groups' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `gr...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `gr...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `gr...')
#3 /var/www/system/Database/BaseBuilder.php(2107): CodeIgniter\Database\BaseConnection->query('INSERT INTO `gr...', Array, false)
#4 /var/www/app/Database/Seeds/IonAuthSeeder.php(33): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#5 /var/www/system/Database/Seeder.php(171): App\Database\Seeds\IonAuthSeeder->run()
#6 /var/www/system/Commands/Database/Seed.php(83): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /var/www/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /var/www/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /var/www/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /var/www/system/CodeIgniter.php(927): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'IonAuthSeeder')
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /var/www/spark(68): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2021-01-14 14:07:27 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /var/www/system/Database/BaseBuilder.php(2107): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /var/www/app/Database/Seeds/IonAuthSeeder.php(52): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#5 /var/www/system/Database/Seeder.php(171): App\Database\Seeds\IonAuthSeeder->run()
#6 /var/www/system/Commands/Database/Seed.php(83): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /var/www/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /var/www/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /var/www/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /var/www/system/CodeIgniter.php(927): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'IonAuthSeeder')
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /var/www/spark(68): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2021-01-14 14:07:27 --> mysqli_sql_exception: Table 'bitnami_app.users_groups' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `us...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /var/www/system/Database/BaseBuilder.php(2107): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /var/www/app/Database/Seeds/IonAuthSeeder.php(64): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#5 /var/www/system/Database/Seeder.php(171): App\Database\Seeds\IonAuthSeeder->run()
#6 /var/www/system/Commands/Database/Seed.php(83): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /var/www/system/CLI/Commands.php(70): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /var/www/system/CLI/CommandRunner.php(80): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /var/www/system/CLI/CommandRunner.php(58): CodeIgniter\CLI\CommandRunner->index(Array)
#10 /var/www/system/CodeIgniter.php(927): CodeIgniter\CLI\CommandRunner->_remap('index', 'db:seed', 'IonAuthSeeder')
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/system/CLI/Console.php(61): CodeIgniter\CodeIgniter->run()
#14 /var/www/spark(68): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2021-01-14 14:08:20 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:08:20 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:08:20 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
ERROR - 2021-01-14 14:08:37 --> mysqli_sql_exception: Table 'bitnami_app.users' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT `email`,...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `email`,...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `email`,...')
#3 /var/www/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `email`,...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(892): CodeIgniter\Database\BaseBuilder->get()
#5 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#6 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#7 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#8 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#9 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#10 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#12 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#13 {main}
ERROR - 2021-01-14 14:08:37 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('SELECT COUNT(*)...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 /var/www/system/Database/BaseBuilder.php(1966): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1058): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1024): IonAuth\Models\IonAuthModel->getAttemptsNum('administrator', '127.0.0.1')
#6 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(894): IonAuth\Models\IonAuthModel->isMaxLoginAttemptsExceeded('administrator')
#7 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#8 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#9 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#10 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#11 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#12 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#14 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#15 {main}
ERROR - 2021-01-14 14:08:37 --> mysqli_sql_exception: Table 'bitnami_app.login_attempts' doesn't exist in /var/www/system/Database/MySQLi/Connection.php:314
Stack trace:
#0 /var/www/system/Database/MySQLi/Connection.php(314): mysqli->query('INSERT INTO `lo...')
#1 /var/www/system/Database/BaseConnection.php(697): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `lo...')
#2 /var/www/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `lo...')
#3 /var/www/system/Database/BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(1145): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /var/www/CodeIgniter-Ion-Auth/Models/IonAuthModel.php(954): IonAuth\Models\IonAuthModel->increaseLoginAttempts('administrator')
#6 [internal function]: IonAuth\Models\IonAuthModel->login('administrator', 'password', false)
#7 /var/www/CodeIgniter-Ion-Auth/Libraries/IonAuth.php(104): call_user_func_array(Array, Array)
#8 /var/www/CodeIgniter-Ion-Auth/Controllers/Auth.php(138): IonAuth\Libraries\IonAuth->__call('login', Array)
#9 /var/www/system/CodeIgniter.php(931): IonAuth\Controllers\Auth->login()
#10 /var/www/system/CodeIgniter.php(427): CodeIgniter\CodeIgniter->runController(Object(IonAuth\Controllers\Auth))
#11 /var/www/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /var/www/public/index.php(44): CodeIgniter\CodeIgniter->run()
#13 /var/www/system/Commands/Server/rewrite.php(45): require_once('/var/www/public...')
#14 {main}
